### ISSUE TITLE
Error with "se_internal_license_for_system_tests" file in license directory

### ISSUE THREAD

**Issue by rahulkumar-das** [mida-project/eye-tracker-setup#1]
Hi,

I have installed all the required libraries and followed the instructions as mention. While I run the `main.py` file it gives me an error "`NoneType`' object has no attribute '`apply_licenses`'". While analyzing the code the file size of the `se_internal_license_for_system_tests` file is 0kb. If anyone would help me to resolve this error it will be great.

Error in `def apply_licenses` (eyetracker).

Thank you.

**Comment by rahulkumar-das** [comment]
In the `main.py` file in that:

```python
def main():
  eyetracker = find_eyetrackers_meta()
```
None is stored in eye-tracker variable. I think the issue is with `find_eyetrackers_meta()` method.

**Comment by FMCalisto** [comment]
Dear @rahulkumar-das,

First of all, it is an honor to see that our work is supporting others work. Unfortunately, the presented solution is limited among the use of the [Tobii SDK](https://www.tobiipro.com/product-listing/tobii-pro-sdk/). If you still want to contribute by fixing our solution, please be free to do it. You can open a pull-request and, for sure, we will accept it. Nevertheless, we developed another solution that we hope to help you. You can access our [`eye-tracker-naive`](https://github.com/mida-project/eye-tracker-naive) repository.

Again, I hope to help you with this. Any question, please do not hesitate to ask us.
