### ISSUE TITLE
Apply for a license

### ISSUE THREAD

**Issue by Asheonea** [mida-project/eye-tracker-setup#2]
Dear Tobii company, we want to transmit the test data of eye tracker, scanning point, gaze point and other categories to clinical medical research, and hope to get a license. be deeply grateful.

**Comment by FMCalisto** [comment]
As soon as you have some achievements, please share with us. Moreover, be free to pull request some of your solving points here.

**Comment by WkangLiu** [comment]
Dear Tobii company, we want to transmit the test data of eye tracker, scanning point, gaze point and other categories to driver attention analysis research, and hope to get a license. be deeply grateful.

**Comment by FMCalisto** [comment]
What do you need exactly?

**Comment by WkangLiu** [comment]
I hope to obtain some data by using the tobii ET 4c/5+license to analyze drivers' concerns about road conditions in the computer's driving simulator software.

**Comment by WkangLiu** [comment]
> What do you need exactly?

I hope to obtain some data by using the tobii ET 4c/5+license to analyze drivers' concerns about road conditions in the computer's driving simulator software.

**Comment by WkangLiu** [comment]
Looking forward to your reply, how can I apply for a license to get the data

**Comment by FMCalisto** [comment]
You need to contact the Tobii company or try to from [here](https://www.tobii.com/products). Hope that helps!

**Comment by WkangLiu** [comment]
Thank you!!
