### ISSUE TITLE
Apply for a license

### ISSUE THREAD

**Issue by WkangLiu** [mida-project/eye-tracker-setup#3]
Dear Tobii company, we want to transmit the test data of eye tracker, scanning point, gaze point and other categories to driver attention analysis research, and hope to get a license. be deeply grateful.

**Comment by FMCalisto** [comment]
You have the [same issue duplicated](https://github.com/mida-project/eye-tracker-setup/issues/2). Please try to be more precise and do not duplicate issues. Thank you!
